### PR TITLE
Fix: whitespace error

### PR DESCRIPTION
**Pull request by ZeeshanGeoPk**
The whitespaces were being removed from the transcription. Resulting in the transcription, with only characters collapsed with each other.

### CODE REVIEW

**Comment by yeyupiaoling** [comment]
@ZeeshanGeoPk Thanks for the pr, But your modification is not correct.

**Comment by ZeeshanGeoPk** [comment]
Can you explain the use of line that I removed?

**Comment by yeyupiaoling** [comment]
The first one is to remove excess spaces, Chinese does not require spaces.
The second one is to decompress the downloaded dataset.

**Comment by yeyupiaoling** [comment]
@ZeeshanGeoPk 非常感谢您的PR，但是您修改的代码并不符合需求，所以先关了您的PR，如有更好的修改，欢迎再次提交PR。

**Pull request closed without merging**
